# Generated by Django 6.0.5 on 2026-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
