# Generated by Django 6.0.5 on 2026-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_audioresource_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioresource',
            options={'verbose_name': 'audio resource', 'verbose_name_plural': 'audio resources'},
        ),
        migrations.AlterField(
            model_name='audioresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='audioresource',
            name='file',
            field=models.FileField(upload_to='audio/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='audioresource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='audioresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
