# Generated by Django 6.0.5 on 2026-05-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0003_alter_audioresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioresource',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='file size'),
        ),
    ]
