# Generated by Django 6.0.5 on 2026-05-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_audioresource_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioresource',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
