# Generated by Django 6.0.5 on 2026-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0005_audioresource_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioresource',
            name='bitrate',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='bitrate'
            ),
        ),
        migrations.AddField(
            model_name='audioresource',
            name='channels',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='channels'
            ),
        ),
        migrations.AddField(
            model_name='audioresource',
            name='sample_rate',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='sample rate'
            ),
        ),
    ]
