# Generated by Django 6.0.5 on 2026-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0006_audioresource_bitrate_audioresource_channels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.ImageField(upload_to='images/', verbose_name='file')),
                (
                    'file_size',
                    models.PositiveIntegerField(default=0, verbose_name='file size'),
                ),
                (
                    'width',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='width'
                    ),
                ),
                (
                    'height',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='height'
                    ),
                ),
                (
                    'format',
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name='format'
                    ),
                ),
                (
                    'color_mode',
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name='color mode'
                    ),
                ),
                (
                    'icc_profile',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='ICC profile',
                    ),
                ),
                (
                    'taken_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='taken at'
                    ),
                ),
                (
                    'camera_make',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='camera make'
                    ),
                ),
                (
                    'camera_model',
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name='camera model',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
            ],
            options={
                'verbose_name': 'image resource',
                'verbose_name_plural': 'image resources',
            },
        ),
    ]
