# Generated by Django 6.0.5 on 2026-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0007_imageresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='videos/', verbose_name='file')),
                (
                    'file_size',
                    models.PositiveIntegerField(default=0, verbose_name='file size'),
                ),
                (
                    'poster',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='video_posters/',
                        verbose_name='poster',
                    ),
                ),
                (
                    'duration',
                    models.DurationField(
                        blank=True, null=True, verbose_name='duration'
                    ),
                ),
                (
                    'width',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='width'
                    ),
                ),
                (
                    'height',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='height'
                    ),
                ),
                (
                    'bitrate',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='bitrate'
                    ),
                ),
                (
                    'video_codec',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='video codec'
                    ),
                ),
                (
                    'frame_rate_num',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='frame rate numerator'
                    ),
                ),
                (
                    'frame_rate_den',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='frame rate denominator'
                    ),
                ),
                (
                    'audio_codec',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='audio codec'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
            ],
            options={
                'verbose_name': 'video resource',
                'verbose_name_plural': 'video resources',
            },
        ),
    ]
