# Generated by Django 6.0.5 on 2026-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0009_resource_base_and_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='produced_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='produced at'
            ),
        ),
    ]
