# Generated by Django 6.0.5 on 2026-05-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0010_resource_produced_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioresource',
            name='bitrate',
        ),
        migrations.RemoveField(
            model_name='audioresource',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='audioresource',
            name='sample_rate',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='camera_make',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='camera_model',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='color_mode',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='format',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='icc_profile',
        ),
        migrations.RemoveField(
            model_name='imageresource',
            name='taken_at',
        ),
        migrations.RemoveField(
            model_name='videoresource',
            name='audio_codec',
        ),
        migrations.RemoveField(
            model_name='videoresource',
            name='bitrate',
        ),
        migrations.RemoveField(
            model_name='videoresource',
            name='frame_rate_den',
        ),
        migrations.RemoveField(
            model_name='videoresource',
            name='frame_rate_num',
        ),
        migrations.RemoveField(
            model_name='videoresource',
            name='video_codec',
        ),
    ]
